    <?php include("global/header.phtml"); ?>


    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    Page Heading
                    <small>Secondary Text</small>
                </h1>

               <!-- Blog Post -->
               <?php foreach ($article as $key => $value): ?>
                <h2>
                    <a href="index.php?page=article&amp;id=<?php echo $value['id'];?>">
                    <?php
                        echo $value['titre'];
                        echo "<br>";
                   ?>
                    </a>
                </h2>
                <p class="lead">
                    by <a href="index.php"><?php echo $value['auteur']; ?></a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posted on <?php echo $value['date_article']; ?></p>
                <hr>
                <img class="img-responsive" src="<?php echo ROOT_IMG.$value['image']; ?>" alt="">
                <hr>
                <p><?php echo $value['description']; ?></p>
                <a class="btn btn-primary" href="index.php?page=article&amp;id=<?php echo $value['id'];?>">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
                <?php endforeach; ?>

                <hr>

                <!-- Pager -->
                <ul class="pager">
                    <li class="previous">
                        <a href="#">&larr; Older</a>
                    </li>
                    <li class="next">
                        <a href="#">Newer &rarr;</a>
                    </li>
                </ul>

            </div>



    <?php include("global/sidebar.phtml"); ?>
    


    <?php include("global/footer.phtml"); ?>

      