 <?php include("global/header.phtml"); ?>

 <!-- Page Content -->
 <div class="container">

    <div class="row">

        <!-- Blog Post Content Column -->
        <div class="col-lg-8">

            <!-- Blog Post -->

            <?php foreach ($pageArticle as $key => $value): ?>

            <!-- Title -->
            <h1><?php echo $value['titre']; ?></h1>

            <!-- Author -->
            <p class="lead">
                by <a href="#"><?php echo $value['auteur']; ?></a>
            </p>

            <hr>

            <!-- Date/Time -->
            <p><span class="glyphicon glyphicon-time"></span> Posted on <?php echo $value['date_article']; ?></p>

            <hr>

            <!-- Preview Image -->
            <img class="img-responsive" src="<?php echo ROOT_IMG.$value['image']; ?>" alt="">

            <hr>

            <!-- Post Content -->
            <p class="lead"><?php echo $value['description']; ?></p>

            <hr>

            <?php endforeach; ?>

            <!-- Blog Comments -->

            <!-- Comments Form -->
            <div class="well">
                <h4>Votre commentaire:</h4>
                <form role="form" method="POST">
                    <div class="form-group">
                        <label>Auteur</label>
                        <input type="text" name="autor" placeholder="your name"><br> 
                        <div class="rate"></div><br>
                        <textarea class="form-control" rows="3" name="content"></textarea>
                    </div>

                <?php if(empty($errors) == false): ?>
                   <div class="alert alert-danger">
                        <ul>
                           <?php foreach ($errors as $key => $value): ?>
                                <li><?php echo $errors[$key];?></li>
                        </ul><?php endforeach; ?>
                    </div> 
                 <?php endif; ?>

                <?php if(empty($success) == false): ?>
                   <div class="alert alert-success">
                        <p>Votre commentaire a bien été créé</p>
                    </div> 
                 <?php endif; ?>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>

            <hr>

            <!-- Posted Comments -->

            <!-- Comment -->
            <?php foreach ($comment as $key => $value): ?>
            <div class="media">
                <a class="pull-left" href="#">
                    <img class="media-object" src="http://placehold.it/64x64" alt="">
                </a>
                <div class="media-body">
                    <h4 class="media-heading"><?php echo $value['auteur']; ?>
                        <div class="fixedRate" data-score="<?php echo $value['note'];?>"></div>
                        <small><?php echo $value['date_commentaire']; ?></small>
                    </h4>
                    <?php echo htmlentities($value['contenu']); ?>
                </div>
            </div>
            <?php endforeach; ?>

        </div>
        
        <?php include("global/sidebar.phtml"); ?>

    </div>

</div>





<?php include("global/footer.phtml"); ?>
