 <?php include("global/header.phtml"); ?>

    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>Mes catégories</h1>
            <p>Les internautes de la communauté photos vous racontent en images leurs vacances inoubliables. Voici leurs carnets de voyage. Vous aussi, partagez vos vacances avec les lecteurs et vous ferez peut-être la une de GEO.fr. </p>
          </div>

          <div class="row">
          	<?php foreach ($categories as $key => $value): ?>
            <div class="col-xs-6 col-lg-4">
              <h2><?php echo $value['titre']; ?></h2>
              <p><?php echo $value['description']; ?> </p>
              <p><a class="btn btn-default" href="index.php?page=unecategorie&amp;id=<?php echo $value['id'];?>" role="button">Voir la catégorie </a></p>
            </div><!--/.col-xs-6.col-lg-4--><?php endforeach; ?>
          </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
        	 <?php foreach ($categories as $key => $value): ?>
          <div class="list-group">
            <a href="index.php?page=unecategorie&amp;id=<?php echo $value['id'];?>" class="list-group-item"><?php echo $value['titre']; ?></a>
          </div><?php endforeach; ?>
        </div><!--/.sidebar-offcanvas-->
      </div><!--/row-->

      <hr>

 <?php include("global/footer.phtml"); ?>
