    <?php include("global/header.phtml"); ?>



    <!-- Page Content -->
    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron hero-spacer">
            <h1>Articles de la catégorie <?php echo $titreCategorie['titre'];?></h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.</p>
            <p><a href="index.php?page=categories" class="btn btn-primary btn-large">Retour</a>
            </p>
        </header>

        <hr>

        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                <h3>Latest Features</h3>
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Features -->
        <div class="row text-center">

            <?php foreach ($pageCategorie as $key => $value): ?>
            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="<?php echo ROOT_IMG.$value['image']; ?>" alt="">
                    <div class="caption">
                        <h3><?php echo $value['titre']; ?></h3>
                        <p><?php echo $value['description']; ?></p>
                        <p>
                           <a href="index.php?page=article&amp;id=<?php echo $value['id_categorie'];?>" class="btn btn-default">Lire l'article</a>
                        </p>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>

        </div>
        <!-- /.row -->

        <hr>


<?php include("global/footer.phtml"); ?>