  <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?=ROOT_JS;?>jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?=ROOT_JS;?>bootstrap.min.js"></script>

    <!-- jQuery Raty -->
    <script type="text/javascript">
        var imgRaty= "<?php echo ROOT_LIB.'images';?>";
        </script>
    <script src="<?=ROOT_LIB;?>jquery.raty.js"></script>
    <script src="<?=ROOT_JS;?>commentaire.js"></script>


</body>

</html>
