 <?php

    $sql="SELECT * FROM `categorie`";
    $requete=$connexion->prepare($sql);
    $requete->execute();
    $sidebarCategories = $requete->fetchAll(PDO::FETCH_ASSOC);
    //var_dump($sidebarCategories);

 ;?>

    <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                        <?php foreach ($sidebarCategories as $key => $value): ?>
                        <?php if($value['id'] <= "4"): ?>
                            <ul class="list-unstyled">
                                <li><a href="index.php?page=unecategorie&amp;id=<?php echo $value['id'];?>"><?php echo $value['titre']; ?></a>
                                </li>
                            </ul>
                        <?php endif; ?>
                        <?php endforeach; ?>
                        </div>
                        <!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                        <?php foreach ($sidebarCategories as $key => $value): ?>
                        <?php if($value['id'] > "4"): ?>
                            <ul class="list-unstyled">
                                <li><a href="index.php?page=unecategorie&amp;id=<?php echo $value['id'];?>"><?php echo $value['titre']; ?></a>
                                </li>
                            </ul>
                         <?php endif; ?>
                        <?php endforeach; ?>
                        </div>
                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
        <!-- /.row -->

        <hr>